# Generated by Django 2.0.7 on 2018-09-25 09:28

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180726_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(default='cover_imgs/default_cover.jpg', upload_to='cover_imgs/%y/%m/%d', verbose_name='头像'),
        ),
    ]
