# Generated by Django 2.0.7 on 2018-09-25 09:46

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(default='cover_imgs/qq1.gif', upload_to='cover_imgs/%y/%m/%d', verbose_name='封面'),
        ),
    ]
