# Generated by Django 2.0.7 on 2018-08-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar_imgs/default.jpg', upload_to='avatar_imgs/%y/%m/%d', verbose_name='头像'),
        ),
    ]
